[navbar.style]
background = "#d5d6db"
foreground = "#343b58"

[navbar.border]
style = "rounded"
color = "#9699a3"

[navbar.tabs]
active_fg       = "#2959aa"
active_modifier = ["bold"]
inactive_fg     = "#6c7086"

[search.style]
background = "#d5d6db"
foreground = "#343b58"
prompt_fg  = "#2959aa"

[search.border]
style = "rounded"
color = "#9699a3"

[results.style]
background = "#d5d6db"
foreground = "#343b58"

[results.selected]
background = "#b4c2f0"
foreground = "#343b58"
modifier   = ["bold"]
symbol     = ">> "
