name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  publish:
    name: Binary Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Build Binary
        run: cargo build --release

      - name: Package Binary
        run: |
          TAG_NAME=${{ github.ref_name }}
          VERSION=${TAG_NAME#v}
          cd target/release
          tar -czvf "latui-${VERSION}-x86_64.tar.gz" latui

      - name: Create Release and Upload Asset
        uses: softprops/action-gh-release@v2
        with:
          files: target/release/latui-*.tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
